### ISSUE TITLE
Feature Request: Limit By Domain

### ISSUE THREAD

**Issue by revett** [M-Reimer/toggleanigif#10]
### Problem

Would it be possible to have configuration within the extension that limits the functionality to a given domain.

For example:

```
tenor.com
giphy.com
```

**Comment by M-Reimer** [comment]
Sorry, but this is out of scope for my Add-on. All I do is toggling a global Firefox setting which always affects all domains. Doing this only for some domains would require way more work and way more code which should then preferably done in a completely new Add-on.

**Comment by revett** [comment]
Understandable, thanks for the explanation 👍
