### ISSUE TITLE
Feature Request: Keyboard Shortcut

### ISSUE THREAD

**Issue by revett** [M-Reimer/toggleanigif#11]
### Problem

Would it be possible to have a keyboard shortcut to toggle the extension on/off.

**Comment by M-Reimer** [comment]
All my Add-ons (or at least most of them) have keyboard shortcuts using the standard Firefox built-in shortcut manager. Please have a look at this: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by revett** [comment]
Thanks 👍
