### ISSUE TITLE
Feature: Toggle per tab

### ISSUE THREAD

**Issue by peter-kehl** [M-Reimer/toggleanigif#12]
Thank you for Toggle Animated Gif, Manuel.

Please, consider toggling per tab.
This would NOT be as difficult as #5 nor #10 - no need to store the URL/domain. I believe Tab API allows you to store per-tab info.

Happy New Year.

**Comment by M-Reimer** [comment]
> This would NOT be as difficult as #5 nor #10 - no need to store the URL/domain.

Why do you think so? If you have a solution which makes it easily possible without rewriting the whole Add-on, then I would be happy to review your pull request.

> I believe Tab API allows you to store per-tab info.

This is the API that I use:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/imageAnimationBehavior
And all it has are the options

- "normal": the default. Play animated images as normal.
- "none": don't animate images at all.
- "once": play the animation once.

And whatever you set there **always applies globally**!

The only way to stop GIF animations "not global" would be to not use any helping API at all but to hook into the web traffic, catch all images with the "GIF" content type, parse the GIF to find out if it is animated, then fetch the first frame of the animation and repackage this single frame as a new binary stream of a "non animated GIF" for the browser to display. That is not easy at all.

> Happy New Year.

Thank you, the same to you!

**Comment by M-Reimer** [comment]
In case someone stumbles across this issue: The only way I can think of doing any "non global" GIF image toggling would be to use https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onHeadersReceived to hook into web requests.

From there on there may be two possible solutions.

1. Block the request, load the image in advance, render it into an https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image and capture the result. Then make a "data:" URL from it and redirect the request to it.
2. Call https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData on the request to get access to the actual image data. From there it should be possible to get a "blob:" URL from the intercepted binary stream to, again, render it into an Image. The captured Image can then be forwarded as the filtered result.

In any case this is an approach that is incompatible with what my Add-on wants to do. All I wanted to provide is an "keep it simple" Add-on which just toggles a setting provided by the Mozilla API.

This means that this would have to be a new Add-on. Maybe named "Toggle Ani GIF (Tab)" or whatever.
