### ISSUE TITLE
Feature Request: Extension for Chrome

### ISSUE THREAD

**Issue by mile59** [M-Reimer/toggleanigif#14]
It would be perfect if this extension was also available in Chrome!
Thanks,

**Comment by M-Reimer** [comment]
Sorry but I won't develop for a browser that I don't use and also would never recommend to anyone.

**Comment by J3ekir** [comment]
> It would be perfect if this extension was also available in Chrome! Thanks,

Chrome already has its own [official version](https://chromewebstore.google.com/detail/animation-policy/ncigbofjfbodhkaffojakplpmnleeoee). It's also in the [source code](https://source.chromium.org/chromium/chromium/src/+/main:ui/accessibility/extensions/animation).
