### ISSUE TITLE
Question: Disabling animations on APNG & WebP formats

### ISSUE THREAD

**Issue by Aleksandra0056** [M-Reimer/toggleanigif#18]
Hello, would it be possible to implement options for affecting also APNG & WebP formats in this extension by disabling the animations on them?

It would have an advantage in websites which are showing multiple animated PNG and/or animated WebP file formats.

**Comment by M-Reimer** [comment]
Actually it already does. Just tried.

All my Add-on does is toggling a Firefox setting. But this setting seems to cover all image formats.

So I guess all that's needed is a new name for the Add-on.

**Comment by Aleksandra0056** [comment]
> Actually it already does. Just tried.
> 
> All my Add-on does is toggling a Firefox setting. But this setting seems to cover all image formats.
> 
> So I guess all that's needed is a new name for the Add-on.

Yes, it works for APNG & animated WebP perfectly.

**Comment by M-Reimer** [comment]
No, I didn't know that there is anything besides animated GIF. And all my Add-on does is toggling one setting.

I'll keep the short name as changing this will change the URL on addons.mozilla.org but rename the Add-on to "Toggle Image Animations"
