### ISSUE TITLE
does not work with FF 69.0 (64bit)

### ISSUE THREAD

**Issue by bstecklum** [M-Reimer/toggleanigif#3]
upon loading https://twitter.com/cosmos4u/ all GIF animations play with gif off

**Comment by M-Reimer** [comment]
I had a look at this page and couldn't find any GIF animation.
Please give a link which points directly to some problematic animation.

The page **does** have some videos. These are **not** GIF animations and so they are not disabled with my "Toggle animated GIF" Addon.

**Comment by M-Reimer** [comment]
I guess the animations, you saw, were no GIF animations (which is the only animation covered by this addon).

If you are sure GIF toggling fails, then please reopen with an URL directly to the tweet with the GIF animation, so I can check this.
