### ISSUE TITLE
Does "on" mean that it is blocking animated gifs or not?

### ISSUE THREAD

**Issue by Tectract** [M-Reimer/toggleanigif#4]
I don't know whether "on" means that it is blocking gifs or not. I'm still getting animation on youtube when I onmouseover a video so it doesn't seem like it's blocking gifs, to me.

**Comment by M-Reimer** [comment]
That's most probably not a GIF but a real video.

But to answer the question: "On" means animated gif files are enabled.

**Comment by Tectract** [comment]
On should mean animated gifs are DISABLED. The point of this add-on is to DISABLE animated gifs, right? It should at least be clarified, somewhere, lol.

**Comment by M-Reimer** [comment]
The point is to toggle the status of them and "on" means "on".

The tooltip even says "Animate GIF (on)" so animated GIF's are **on**.

**Comment by Tectract** [comment]
If the purpose of the addon is to block animated gifs, then "on" should mean it's blocking animated gifs. Tooltips are bad design. Instead of "on/off" you should instead use "blocking/allowed" to make it clear. Or add something that tells people whether "on" means it's blocking gifs or not.

**Comment by M-Reimer** [comment]
Actually it does not block anything. It toggles a setting:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/imageAnimationBehavior

I have many such "toggle add-ons" and they all behave the same and they all have "on" when the toggled setting is "on" and "off" if the toggled setting is "off".
