### ISSUE TITLE
Stop indiviual images in a page

### ISSUE THREAD

**Issue by retog** [M-Reimer/toggleanigif#7]
Some animations are actually quite useful, only if they go on an on they become distracting. I would like to be able to right-click on an animated image and choose to stop the animation.

**Comment by BoomerangAide** [comment]
An [add-on](https://github.com/simonlindholm/toggle-gifs) for Firefox used to have more flexibility (ability to pause and restart individual images on the page and all), but Mozilla killed it in Firefox 57 when they went [webextension only](https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/).
Maybe an alternative browser that still support old style extensions could do it (I think of Seamonkey, but could be wrong, and/or they could be others).

**Comment by M-Reimer** [comment]
Stopping individual images could be possible with the latest API state on Firefox.
But I'm talking about **stopping** I don't want to make things too complex. What I'm thinking of is a "Freeze animation" context menu entry. Clicking it freezes the image animation until the page is reloaded.
