### ISSUE TITLE
Animation not being stopped on Mac FF 95.0.2 64-bit

### ISSUE THREAD

**Issue by jeffory-orrok** [M-Reimer/toggleanigif#9]
I have tried reloading the page and even quitting and restarting FF but this image never stops animating https://gitlab.com/itentialopensource/pre-built-automations/archive-job-data#how-to-install

**Comment by jazzbeauster** [comment]
Same for me on MacBook Pro (16-inch, 2021 with M1 Pro) running Monterey 12.1

Really need this to work, before I strangle a dancing cat!!!

**Comment by M-Reimer** [comment]
Works for me. If I do a regular "reload", then animation freezes at the last frame it was at. If I do "Shift + Reload", then it freezes at the first frame.

**Comment by M-Reimer** [comment]
This issue is open for years, now.
As I can't even test this and so far have not got any newer feedback from Mac users, I'll close this, now.

**Comment by jazzbeauster** [comment]
Thanks for remembering.  Apple has fixed the problem with an OS preference.  Accessibility––Display––Auto-play Animated Images [turn off]
